version: '3.8'

services:
  app:
    image: ambientum/php:7.4-nginx
    container_name: clean_arch_app
    restart: always
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:8080
    networks:
      - clean_arch_network
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    container_name: clean_arch_db
    restart: always
    networks:
      - clean_arch_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .db.env

volumes:
  pgdata:

networks:
  clean_arch_network:
    driver: bridge

